# Create a new GitHub release when tags are pushed to the repository
name: "Create Tagged Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Create Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      # Only create release tags for stem branch
      - name: Check if is production branch
        if: ${{ endsWith(github.event.base_ref, 'stem') == false }}
        run: exit -1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: stem
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: Install dependencies ðŸ“¥
        run: npm ci
      - name: Check if current version already exists
        run: npm run checkVersion
      - name: Build & Test package ðŸ”§
        run: npm run build && npm run test
      

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TAG_RELEASE_GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            *.md
